package examenmarzo;
// Generated 27-feb-2018 15:41:14 by Hibernate Tools 4.3.1


import java.text.DateFormat;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {
    
    private int clave;
    private DateFormat fecha;
    private String asignatura;
    private String texto;

    public Examen() {
    }
    
    public Examen(int clave) {
        this.clave = clave;
    }
    
    public Examen(int clave, DateFormat fecha, String asignatura, 
            String texto) {
       this.clave = clave;
       this.fecha = fecha;
       this.asignatura = asignatura;
       this.texto = texto;
       
    }
   
    public int getClave() {
        return this.clave;
    }
    
    public void setClave(int clave) {
        this.clave = clave;
    }
    public DateFormat getFecha() {
        return this.fecha;
    }
    
    public void setFecha(DateFormat fecha) {
        this.fecha = fecha;
    }
    public String getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(String asignatura) {
        this.asignatura = asignatura;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
}


